version: '3'

services:
        ssh0:
                build: .
                container_name: ssh0
                hostname: ssh0.cluster22
                networks:
                        clusterExec:
                                ipv4_address: 172.22.0.10

        ssh1: 
                build: .
                container_name: ssh1
                hostname: ssh1.cluster22
                networks:
                        clusterExec:
                                ipv4_address: 172.22.0.11
        ssh2: 
                build: .
                container_name: ssh2
                hostname: ssh2.cluster22
                networks:
                        clusterExec:
                                ipv4_address: 172.22.0.12

        ssh3: 
                build: .
                container_name: ssh3
                hostname: ssh3.cluster22
                networks:
                        clusterExec:
                                ipv4_address: 172.22.0.13
                                

networks:
        cluster22:
                driver: bridge
                ipam:
                        driver: default
                        config:
                         -
                                subnet: 172.22.0.0/16
