language: go

go:
        - "1.9"
        - "1.10"
        - master


before_install: 
        - ssh-keygen -t rsa -f ./test_key -q -N ""
        - docker build -t ssh22 ./ci/ssh22/
        - docker build -t ssh25 ./ci/ssh25/
        - docker run -d -h ssh22 --name ssh22  -p 22:22 ssh22 
        - docker run -d -h ssh25 --name ssh25 -p 25:25  ssh25

install: ./ci/keyexchange.sh

